ror/rails_with_bootstrap/config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :todos

end

ror/rails_with_bootstrap/app/models/product.rb
class Product < ActiveRecord::Base
end

ror/rails_with_bootstrap/app/models/todo.rb
class Todo < ActiveRecord::Base
end

ror/rails_with_bootstrap/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ror/rails_with_bootstrap/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :featImage, :description, :price)
    end
end

ror/rails_with_bootstrap/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:title, :description, :completed)
    end
end

ror/rails_with_bootstrap/app/helpers/application_helper.rb
module ApplicationHelper
end

ror/rails_with_bootstrap/app/helpers/products_helper.rb
module ProductsHelper
end

ror/rails_with_bootstrap/app/helpers/todos_helper.rb
module TodosHelper
end

ror/rails_with_bootstrap/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsWithBootstrap</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

	<!-- Latest compiled and minified CSS -->
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous"> -->

<!-- Optional theme -->
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous"> -->

</head>
<body>

	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapsibleMenu">
					<span class=icon-bar></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a href="#" class="navbar-brand">OnlineShopping</a>
			</div>
			<div class="collapse navbar-collapse" id="collapsibleMenu">
				<ul class="nav navbar-nav navbar-right">
					<li><a href="#" data-target="#shoppingCart" data-toggle="modal"><span class="glyphicons glyphicon-shopping-cart"></span></a></li>
					<li><a href="#">Home</a></li>
					<li><a href="#">About</a></li>
					<li><a href="#">Contact</a></li>
					<li><a href="#">Support</a></li>
				</ul>
				<form class="navbar-form navbar-left" role="search">
					<div class="form-group">
						<input type="text" class="form-control" placeholder="Search">
					</div>
					<button type="submit" class="btn btn-default">Submit</button>
				</form>
			</div>
		</div>
	</div>

	<div class="modal fade" id="myModal">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title">Create a Project</h4>
				</div>
				<div class="modal-body">
					<form class="">
						<div class="form-group">
							<input type="text" class="form-control" placeholder="Project Name">
						</div>
						<div class="form-group">
							<input type="textarea" class="form-control" placeholder="Project Description">
						</div>
					</form>
				</div>
				<div class="modal-footer">
					<!-- <button class="btn btn-success" data-dismiss="modal"><i class="glyphicon glyphicon-plus"></i>Create</button> -->
					<a href="#" class="btn btn-primary">Create</a>
				</div>
			</div>
		</div>
	</div>

	<div class="modal fade" id="shoppingCart">
		<div class="modal-dialog modal-lg">
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title text-primary">Your Cart</h4>
					<p class="pull-right text-primary"><b>4 items</b></p>
				</div>
				<div class="modal-body">
					<table class="table table-bordered">
						<tr>
							<th>S1 no</th>
							<th>Item Name</th>
							<th>Unit Price (USD)</th>
							<th>Quantity</th>
							<th>Price</th>
							<th></th>
						</tr>
					</table>
				</div>
				<div class="modal-footer">
					<!-- <button class="btn btn-success" data-dismiss="modal"><i class="glyphicon glyphicon-plus"></i>Create</button> -->
					<a href="#" class="btn btn-primary">Create</a>
				</div>
			</div>
		</div>
	</div>

<div class="container bodyContent">
  <%= yield %>
</div>



<!-- Latest compiled and minified JavaScript -->
<!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script> -->
<!-- <script src="https://code.jquery.com/jquery-1.12.3.min.js" integrity="sha256-aaODHAgvwQW1bFOGXMeX+pC4PZIPsvn2h1sArYOhgXQ=" crossorigin="anonymous"></script> -->


</body>
</html>

ror/rails_with_bootstrap/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :for => "nameField" %>
    <%= f.text_field :name, :class => "form-control", :id => "nameField" %>
  </div>
  <div class="form-group">
    <%= f.label :featImage, :for => "imgField" %>
    <%= f.text_field :featImage, :class => "form-control", :id => "imgField" %>
  </div>
  <div class="form-group">
    <%= f.label :description, :for => "descField" %>
    <%= f.text_area :description, :class => "form-control", :id => "descField" %>
  </div>
  <div class="form-group">
    <%= f.label :price, :for => "priceField" %>
    <%= f.text_field :price, :class => "form-control", :id => "priceField" %>
  </div>
	<ul class="list-inline">
		<li><%= f.submit 'Create', :class => "btn btn-success"%></li>
		<li><%= button_tag "Reset", type: :reset, :class => "btn btn-default"  %></li>
	</ul>
<% end %>

ror/rails_with_bootstrap/app/views/products/edit.html.erb
<div class="page-header">
	<ul class="list-inline pull-right">
		<li><%= link_to 'Show', @product, :class => "btn btn-success" %></li>
		<li><%= link_to 'Back', products_path, :class => "btn btn-default" %></li>
	</ul>
	<h3>Edit product</h3>
</div>

<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
		<%= render 'form' %>
	</div>
</div>

ror/rails_with_bootstrap/app/views/products/index.html.erb
<div class="page-header">
	<%= link_to 'New Product', new_product_path, :class => "btn btn-success pull-right" %>
	<h3>All Products</h3>
</div>

<div class="row">
  <% @products.each do |product| %>
	<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
		<h2><%= product.name %></h2>
		<img class="img-responsive" src="<%= asset_path product.featImage%>" />
    <p><%= product.description %></p>
		<h4><%= product.price %></h4>
		<%= link_to 'Show', product, :class => "btn btn-primary" %>
		<%= link_to 'Buy', "#", :class => "btn btn-success", :data => { :toggle => 'modal', :target => '#myModal'} %>
	</div>
	<% end %>
</div>











<!-- <div class="container">
	<table class="table table-hover ">
	  <thead>
	    <tr>
	      <th>Name</th>
	      <th>Featimage</th>
	      <th>Description</th>
	      <th>Price</th>
	      <th colspan="3"></th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @products.each do |product| %>
	      <tr>
	        <td><%= product.name %></td>
	        <td><%= product.featImage %></td>
	        <td><%= product.description %></td>
	        <td><%= product.price %></td>
	        <td><%= link_to 'Show', product %></td>
	        <td><%= link_to 'Edit', edit_product_path(product) %></td>
	        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
</div>

<br>

<div class="container">
	<form class="form-inline" action="index.html" method="post">
		<div class="form-group">
			<label for="emailField">Email</label>
			<input type="text" class="form-control" placeholder="Enter email">
		</div>
		<div class="form-group has-success has-feedback">
			<label for="passwordField" class="control-label">Password</label>
			<input type="password" class="form-control" placeholder="Enter password">
			<span class="glyphicon glyphicon-ok form-control-feedback"></span>
		</div>
		<div class="checkbox">
			<label><input type="checkbox">Remember me</label>
		</div>
		<button type="submit" class="btn btn-success">Sign in</button>
	</form>
</div> -->

ror/rails_with_bootstrap/app/views/products/new.html.erb
<div class="page-header">
	<%= link_to 'Back', products_path, :class => "btn btn-default pull-right" %>
	<h3>Add New product</h3>
</div>

<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
		<%= render 'form' %>
	</div>
</div>














<!-- <h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %> -->

ror/rails_with_bootstrap/app/views/products/show.html.erb
<!-- <p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Featimage:</strong>
  <%= @product.featImage %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %> -->




<div class="page-header">
	<ul class="list-inline pull-right">
		<li><%= link_to 'Edit', edit_product_path(@product), :class => "btn btn-warning" %></li>
		<li><%= link_to 'Back', products_path, :class => "btn btn-default" %></li>
	</ul>
	<h3><%= @product.name %></h3>
</div>


<table class="table table-striped">
	<tr>
		<td>Name</td>
		<td><%= @product.name %></td>
	</tr>
	<tr>
		<td>Image</td>
		<td><img class="img-responsive" src="<%= asset_path @product.featImage %>" %></td>
	</tr>
	<tr>
		<td>Description</td>
		<td><%= @product.description %></td>
	</tr>
	<tr class="success">
		<td>Price</td>
		<td><%= @product.price %></td>
	</tr>
</table>

ror/rails_with_bootstrap/app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :completed %><br>
    <%= f.check_box :completed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ror/rails_with_bootstrap/app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

ror/rails_with_bootstrap/app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Todos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.title %></td>
        <td><%= todo.description %></td>
        <td><%= todo.completed %></td>
        <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %>

ror/rails_with_bootstrap/app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

ror/rails_with_bootstrap/app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo.description %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @todo.completed %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>