ror/rails_learn/config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'home', 'form', controller: 'pages'

  post :about, controller: 'pages'
  get :math, controller: :pages, path: :new_math

end

ror/rails_learn/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ror/rails_learn/app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
   render 'pages/home' # 可有可無
  end

  def about
		
  end

  def math
    @numbers = (1..46).to_a.sample(6)
  end

end

ror/rails_learn/app/helpers/application_helper.rb
module ApplicationHelper
end

ror/rails_learn/app/helpers/navbar_helper.rb
module NavbarHelper
  def nav_li text, path
    active = request.path == path ? :active : nil
    content_tag :li, link_to(text, path), class: active
  end
end

ror/rails_learn/app/helpers/pages_helper.rb
module PagesHelper
end

ror/rails_learn/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsLearn</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= render 'shared/navbar', line_number: 3 %>
<%= render "albums/album", title: '生活', summary: '日常', image: '...' %>
<%= yield %>

<%= tag :hr %>
<%= content_tag :span, "Text", class: :item %>
<%= link_to "關於我們", about_path, target: :_blank %>

<%= javascript_include_tag 'main' %>
<script src="/assets/main.js"></script>
<script src="/javascripts/main.js"></script>


<%= stylesheet_link_tag 'style' %>
<link rel="stylesheet" href="/assets/style.css" media="screen">
<link rel="stylesheet" href="/stylesheets/style.css" media="screen">

<%= image_tag 'user.png', width: 100 %>
<img src="/assets/user.png" alt="User" width="100"/>
<img src="/images/user.png" alt="User" width="100"/>

</body>
</html>

ror/rails_learn/app/views/shared/_navbar.html.erb
<!-- <ul>
  <li><a href="<%= root_path %>">home page</a></li>
  <li><a href="<%= about_path %>">about</a></li>
  <li><a href="<%= math_path %>">math</a></li>
</ul> -->

<!-- 正規rails 寫法 -->

<ul>
  <%= nav_li 'home page', root_path %>
  <li><%= link_to 'about', about_path %></li>
  <li><%= link_to 'math', math_path %></li>
</ul>

<% line_number.times do %>
<hr>
<% end %>